package com.potatosheep.kite.core.notification

import android.app.Notification

/**
 * Interface for classes that create notifications for Kite.
 */
interface Notifier {
    /**
     * Post a download notification.
     *
     * @param filename the name of the file to be downloaded
     * @param notificationId the ID of the notification
     *
     * @return the [Notification] generated by this function
     */
    fun postDownloadNotification(
        filename: String,
        notificationId: Int,
        state: Int
    ): Notification

    /**
     * Update a download notification.
     *
     * @param notificationId the ID of the target download notification
     * @param state the desired state of the target download notification, such as
     * [Notifier.STATE_DOWNLOADING_IMAGE]
     */
    fun updateDownloadNotification(
        notificationId: Int,
        state: Int
    )

    companion object {
        /**
         * State for when image download is in progress.
         */
        const val STATE_DOWNLOADING_IMAGE = 1
        /**
         * State for when video download is in progress.
         */
        const val STATE_DOWNLOADING_VIDEO = 2
        /**
         * State for when audio download is in progress.
         */
        const val STATE_DOWNLOADING_AUDIO = 4
        /**
         * State for when a download is complete.
         */
        const val STATE_COMPLETE = 5
        /**
         * State for when a download is cancelled.
         */
        const val STATE_STOPPED = 6
    }
}